### ISSUE TITLE
url parse problem?  RESTful style URL or traditional URL

### ISSUE THREAD

**Issue by allenLew1991** [scalr-tutorials/apiv2-examples#3]
when calling openAPI , specified Restful URL , the response result is error endpoint or invalid structure.   How to fix it?

**Comment by AloysAugustin** [comment]
Hi @allenLew1991, could you post the following details:
- The version of Scalr that you are using
- The URL that you are trying to call
- The payload that you are supplying
- The entire error message that you are seeing

Thanks!

**Comment by allenLew1991** [comment]
hello @AloysAugustin ,
Your original example URL   /api/v1beta0/account/os/?family=ubuntu      it works; 
but when using Restful URL  such as $url = '/api/v1beta0/account/1/environments/' ,  response result is
EndpointNotFound. 

At  /master/php/ScalrAPI.php line: 23     Split URL into components
 whether need add judgement about URL format before using parse_url() ?


![isueue02](https://user-images.githubusercontent.com/3362015/30583359-723aa4c4-9d59-11e7-8926-6be05fe6de92.png)

![isueue01](https://user-images.githubusercontent.com/3362015/30583411-95f31fae-9d59-11e7-856b-422fc52a55fc.png)

**Comment by AloysAugustin** [comment]
Thanks for the additional details. The endpoint '/api/v1beta0/account/<accountID>/environments/' was recently changed in Enterprise Scalr, it used to be just '/api/v1beta0/account/environments/'.

Which version of Scalr are you using? You can get the version from the Scalr UI, by clicking on the (?) button in the top right corner, and then (i) About Scalr.
You might have better luck with the '/api/v1beta0/account/environments/' endpoint.

**Comment by allenLew1991** [comment]
Thanks for your reply. I'm using v5.11.22(Community version) . 
I  figured out . This parse_url of apiv2-examples isn't a bug. The [API Document ](https://api-explorer.scalr.com/)and my local source code are out of sync.  I modified setupRoutes()  [()](https://github.com/Scalr/scalr/blob/master/app/src/Scalr/Api/Rest/ApiApplication.php). u-huh, the endpoint goes  right.
